### ISSUE TITLE
"No package policycoreutils-python available."

### ISSUE THREAD

**Issue by wikro** [cloudalchemy/ansible-alertmanager#111]
When running the playbook against a Centos 8 host, I receive the following error:

`failed: [host] (item=policycoreutils-python) => {"ansible_loop_var": "item", "attempts": 5, "changed": false, "failures": ["No package policycoreutils-python available."], "item": "policycoreutils-python", "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}`

Could this be resolved by having the same `centos.yml` and `centos-8.yml` files in the `vars` directory like https://github.com/cloudalchemy/ansible-prometheus/tree/master/vars ?

**Comment by paulfantom** [comment]
This should be solved by porting mechanism from https://github.com/cloudalchemy/ansible-node-exporter/pull/132. At some point (probably around March-April as I don't have time to do it now) this will be a default mechanism across all cloudalchemy roles.

PRs regarding porting that mechanism are welcome :)

**Comment by wikro** [comment]
Done!

https://github.com/cloudalchemy/ansible-alertmanager/pull/112
