### ISSUE TITLE
Http config unable to set basic auth

### ISSUE THREAD

**Issue by mcsammac** [cloudalchemy/ansible-alertmanager#115]
When creating an http config via the default template it is unable to handle using basic auth.  The issue appears to be here: 
``` 
{% if alertmanager_http_config | length %}
  http_config:
{% endif %}
{% for key, value in alertmanager_http_config.items() %}
    {{ key }}: {{ value | quote }}
{% endfor %}
```
I was able to fix it locally by adding a new variable and modifying the template as so:
```
{% if alertmanager_http_config | length %}
  http_config:
{% endif %}
{% if alermanager_http_config_basic_auth | length %}
    basic_auth:
{% for key, value in alermanager_http_config_basic_auth.items() %}
      {{ key }}: {{ value | quote }}
{% endfor %}
{% endif %}
{% for key, value in alertmanager_http_config.items() %}
    {{ key }}: {{ value | quote }}
{% endfor %}
```
Can be fixed by using a custom template, but seems like it should be part of the default.  Would be happy to put in a PR.  Also, it appears that the existence of the `alert_manager_http_config` variable is missing all together from the README.

**Comment by paulfantom** [comment]
This should be changed to something more generic like:
```
{% if alertmanager_http_config | length %}
http_config:
{{ alertmanager_http_config | to_nice_yaml(indent=4) }}
{% endif %}
```
and `alertmanager_http_config` should be added to README.md. Could you create a PR?

**Comment by mcsammac** [comment]
Ok that does make more since.  I changed and tested it.  Just put in the PR.
