### ISSUE TITLE
var name docu mismatch alertmanager_binaries_local_dir 

### ISSUE THREAD

**Issue by appliedprivacy** [cloudalchemy/ansible-alertmanager#130]
The README calls the variable `alertmanager_binaries_local_dir` but it is actually called 
[alertmanager_binary_local_dir](https://github.com/cloudalchemy/ansible-alertmanager/blob/3f4f089cae9fb6cf7a71c27745a3a5e6eac0b929/tasks/preflight.yml#L40). 

This causes playbook fails, when people use the name from the README.

**Comment by paulfantom** [comment]
Proper name should be `alertmanager_binaries_local_dir` as alertmanager tarball contains `amtool` and `alertmanager` binaries and both are required by this role.

Could you create PR?
