### ISSUE TITLE
offline mode fails

### ISSUE THREAD

**Issue by appliedprivacy** [cloudalchemy/ansible-alertmanager#131]
**What happened?**

Even after setting `alertmanager_binary_local_dir` 
the task `"Get checksum for {{ go_arch }} architecture"` gets executed and fails (curl fails because we are offline).

**Did you expect to see some different?**

no failure (task skipped)

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Role version:

3f4f089cae9fb6cf7a71c27745a3a5e6eac0b929

* Ansible version information:

2.9.9

* Variables:

```
alertmanager_binary_local_dir: "alertmanager-0.21.0.linux-amd64"
```

* Ansible playbook execution Logs:

```
TASK [ansible-alertmanager-master : Get checksum for amd64 architecture] *********************************************************************************************************************************************************************
task path: /home/user/ansible/roles/ansible-alertmanager-master/tasks/preflight.yml:46
url lookup connecting to https://github.com/prometheus/alertmanager/releases/download/v0.21.0/sha256sums.txt
fatal: FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'url'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Failed lookup url for https://github.com/prometheus/alertmanager/releases/download/v0.21.0/sha256sums.txt : <urlopen error [Errno -2] Name or service not known>"
}

```

**Comment by OuiSouss** [comment]
Hello, I have detected the same behaviour on my infrastructure.

During my investigation, i notice that the role **ansible-alertmanager** don't have the same behaviour regarding other roles like **ansible-prometheus** and **ansible-node-exporter**.

For example, in **ansible-prometheus** role, this part of "Get checksum" is done like this (file preflight.yml of ansible-prometheus role)[https://github.com/cloudalchemy/ansible-prometheus/blob/master/tasks/preflight.yml] : 

```

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
