### ISSUE TITLE
Tasks "download alertmanager binary to local folder" and "unpack alertmanager binaries" always changed

### ISSUE THREAD

**Issue by meons** [cloudalchemy/ansible-alertmanager#142]
**What happened?**

These tasks are always have changed state in normal and check mode as well. But they shouldn't make noise if alertmanager is already installed.

```console
TASK [cloudalchemy.alertmanager : download alertmanager binary to local folder] ***
changed: [myhost]
TASK [cloudalchemy.alertmanager : unpack alertmanager binaries] ****************
changed: [myhost]
```

**Did you expect to see some different?**

After a first successful run, these tasks shouldn't have changed state in next runs (if there is no changes on host of course).

**How to reproduce it (as minimally and precisely as possible)**:

Install this role on a Ubuntu 20.04.1 LTS.

**Environment**

* Role version:

    `0.19.1`

* Ansible version information:

    `2.10.2`
    

* Variables:

```
insert role variables relevant to the issue
```

* Ansible playbook execution Logs:

```
insert Ansible logs relevant to the issue here
```

**Anything else we need to know?**:

Are the `check_mode: false` statements correctly used here?

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
