### ISSUE TITLE
mute_time_interval support

### ISSUE THREAD

**Issue by micwiel** [cloudalchemy/ansible-alertmanager#146]
**What is missing?**
https://github.com/prometheus/alertmanager/blob/master/docs/configuration.md#mute_time_interval support

**Why do we need it?**
It is already implemented in alertmanager but not available in the role.

**Environment**

* Role version:
0.19.1

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
