### ISSUE TITLE
alertmanager_checksum_url Gives error after commit from 7 day ago

### ISSUE THREAD

**Issue by debeste123** [cloudalchemy/ansible-alertmanager#150]
**What happened?**
After commit https://github.com/cloudalchemy/ansible-alertmanager/commit/6f050af066c541ca85db79c13b69b1defe801ac5
I received following error:

`TASK [ansible-alertmanager : Get checksum for amd64 architecture] **************
fatal: [promcmt-test01]: FAILED! => {"msg": "template error while templating string: expected token 'end of print statement', got 'select'. String: {{ lookup('url', 'https://github.com/prometheus/alertmanager/releases/download/v' + alertmanager_version + '/sha256sums.txt', wantlist=True) | list select('contains', 'linux-' + go_arch + '.tar.gz') | list | first).split(' ')[0] }}"}
...ignoring

TASK [ansible-alertmanager : Checksum lookup error message] ********************
fatal: [promcmt-test01]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'alertmanager_checksum_url' is undefined\n\nThe error appears to be in '/tmp/awx_183634_xomgifxg/requirements_roles/ansible-alertmanager/tasks/preflight.yml': line 51, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Checksum lookup error message\n ^ here\n"}`

**Did you expect to see some different?**

**How to reproduce it (as minimally and precisely as possible)**:

Get latest version of amd64 alertmanager installed

**Environment**

* Role version:

0.21
    `Insert release version/galaxy tag or Git SHA here`

* Ansible version information:

    `ansible --version`
    

* Variables:

```
insert role variables relevant to the issue
```

* Ansible playbook execution Logs:

```
insert Ansible logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by yzdann** [comment]
https://github.com/cloudalchemy/ansible-alertmanager/pull/151

**Comment by debeste123** [comment]
@yzdann  Can you create a tag, from before this new update?

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
