### ISSUE TITLE
Permissions of alertmanager config file

### ISSUE THREAD

**Issue by weakcamel** [cloudalchemy/ansible-alertmanager#152]
**What happened?**

A positive scenario - installation of alertmanager - creates a configuration file, e.g. `/etc/alertmanager/alertmanager.yml`.

The permissions on said config file are as follows:

```
$ ls -ald /etc/alertmanager/alertmanager.yml
-rw-r--r-- 1 alertmanager alertmanager 1050 Apr 30 13:02 /etc/alertmanager/alertmanager.yml
```

which is defined here:

https://github.com/cloudalchemy/ansible-alertmanager/blob/c10f2a88f7d0dd8ac8127e25e0c246ff61c7a1f3/tasks/configure.yml#L18

It is a security problem because alertmanager receivers (e.g.`email_config`) include secrets in plain text which would be visible to every user logged into the Alertmanager host.

**Did you expect to see some different?**

I would expect the config to not be readable by "others", i.e.:
```
$ ls -ald /etc/alertmanager/alertmanager.yml
-rw-r----- 1 alertmanager alertmanager 1050 Apr 30 13:02 /etc/alertmanager/alertmanager.yml
```

**How to reproduce it (as minimally and precisely as possible)**:

Standard task, e.g.

```yaml
    - name: Install Alertmanager
      ansible.builtin.import_role:
        name: cloudalchemy.alertmanager

```

**Environment**

* Role version:

    `0.19.1`

* Ansible version information:

```
$ ansible --version
ansible 2.10.8
  config file = /Users/weakcamel/git/auto/ansible.cfg
  configured module search path = ['/Users/weakcamel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/weakcamel/git/auto/.venv/lib/python3.9/site-packages/ansible
  executable location = /Users/weakcamel/git/auto/.venv/bin/ansible
  python version = 3.9.4 (default, Apr  5 2021, 01:50:46) [Clang 12.0.0 (clang-1200.0.32.29)]
```

* Variables:

```
n/a
```

* Ansible playbook execution Logs:

```
n/a
```

**Anything else we need to know?**:

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
