### ISSUE TITLE
too many open files error 

### ISSUE THREAD

**Issue by ahmadalli** [cloudalchemy/ansible-alertmanager#162]
**What happened?**

```bash
http: Accept error: accept tcp [::]:9093: accept4: too many open files; retrying in 1s
http: Accept error: accept tcp [::]:9093: accept4: too many open files; retrying in 1s
http: Accept error: accept tcp [::]:9093: accept4: too many open files; retrying in 1s
```
is appearing on alertmanager journalctl error, and it stops sending alerts

adding this should fix the error:

```ini
[Service]
LimitNOFILE=16000
LimitNOFILESoft=16000
```

**Comment by SuperQ** [comment]
16k open files seems like a lot for the alertmanager. Can you describe your configuration a little more that would generate this amount?

**Comment by ahmadalli** [comment]
It started happening when I enabled grafana `ngalert` module and added alertmanager to grafana notification channels

**Comment by ahmadalli** [comment]
grafana is hugging all the connections. I guess this should be fixed from the grafana's side
