### ISSUE TITLE
alertmanager_template_files variable config is incorrect

### ISSUE THREAD

**Issue by mehrdad-faridi** [cloudalchemy/ansible-alertmanager#176]
**What happened?**
if you run ansible and you put your alert rules in `template directory` ansible will not copy them, based on the config here:
https://github.com/cloudalchemy/ansible-alertmanager/blob/master/defaults/main.yml#L10

**Did you expect to see some different?**
it should copy all the files(default `*.tmpl`) in to alertmanager template directory(`/etc/alertmanager/templates/`)

* Ansible version information:

    `ansible 2.9.27`

* Variables:
`alertmanager_template_files `
```
insert role variables relevant to the issue
```

* Ansible playbook execution Logs:
TASK [copy alertmanager template files] *****************************************************************************************************
[WARNING]: Unable to find 'alertmanager/templates' in expected paths (use -vvvvv to see paths)

<be><br>
<be><br>

**HOW YOU CAN FIX THIS**:
correct config is:
```yaml
alertmanager_template_files:
  - templates/*.tmpl
```
you have to remove `alertmanager` directory from the path.

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
