### ISSUE TITLE
Service command line flags set during `install` but not during `configure`

### ISSUE THREAD

**Issue by mgrecar** [cloudalchemy/ansible-alertmanager#56]
Not sure this is a bug, but it was an unexpected surprise to me and it's causing me some pain.

I have found that when trying to set the `alertmanager_external_url` value, it is only set when running the `install` tag, and not the `configure` tag.  Digging in, the reason is that the `web.external-url` value is provided to the binary as a command line flag, and that is baked in to the `alertmanager.service` template, which is only done during the install step.

This is a problem for me, because I'm trying to bake AMIs in AWS with most of the installation done ahead of time, and then deployment instantiates these AMIs and applies dynamic configuration to them, things like IP addresses, ports, URLs, etc.  I've found that the setup here makes it so that I really can't do that.

Since those arguments to the binary are really (at least, in my mind) configuration, shouldn't the `configure` task update the flag as appropriate or re-template the service?

**Comment by paulfantom** [comment]
We could move creating systemd service file from `install.yml` to `configure.yml` and this should solve this problem without breaking anything.

Could you prepare a PR?

**Comment by mgrecar** [comment]
https://github.com/cloudalchemy/ansible-alertmanager/pull/57
