### ISSUE TITLE
cluster setup broken in default

### ISSUE THREAD

**Issue by gajowi** [cloudalchemy/ansible-alertmanager#87]
Unless the clustering setup is modified, alertmanager fails with:
"create memberlist: Failed to get final advertise address: No private IP address found, and explicit IP not provided"

This can be avoided by having:
  alertmanager_cluster:
    listen-address: ""
as documented at: https://github.com/prometheus/alertmanager#high-availability
  --cluster.listen-address string: cluster listen address (default "0.0.0.0:9094"; empty string disables HA mode)

I propose this be set as the default.

I suspect this is from a recent upstream change. Maybe: https://github.com/prometheus/alertmanager/commit/78c9ebc621c2f2bd6fc90d351c4e4675b583fe56

CI did not catch this so perhaps it is testing successful deployment but not successful service startup.

I could make a PR for the proposed  (trivial!) default change, but I'm not yet well positioned to delve into the CI setup.

**Comment by paulfantom** [comment]
That would also explain the problems @dmke had in #74.

@simonpasquier do we now have a requirement in alertmanager to specify `--cluster.listen-address` when using external url? Also is alertmanager now starting in HA mode by default? If not, I think we have a bug.

**Comment by paulfantom** [comment]
Ideally, we should specify the same default options as [alertmanager container image](https://github.com/prometheus/alertmanager/blob/master/Dockerfile#L20-L21) uses. There are some caveats though, for example, we shouldn't remove `alertmanager_web_listen_address`. I don't think setting anything in `cluster.*` by default is a proper way of setting up alertmanager. Instead, we should probably do something with `*_web_external_url` variables. I see a couple of options:

1) Remove all logic regarding that variable and merge it into `alertmanager_config_flags_extra`. This can be done in `tasks/preflight.yml` to maintain backward compatibility. Before role reaches 1.0 release we can get rid of dirty backward compatibility hacks.

2) Set it to an empty string by default and add conditionals in systemd service template.

2.1) Add a preflight check to assert that the passed address is an external one.


The first option makes it cleaner as `alertmanager_web_external_url` isn't treated as a special parameter, the second one allows us to make some assertions during role run.

**Comment by gajowi** [comment]
Can 'we' confirm if the alertmanager container image has the same problem? I guess I could do that, but first I have to understand how to run the latest version from quay.io and if it is recent enough. I've not used quay.io before.  It might be best if someone else tests. Does it have the same error with no extra configuration?

**Comment by paulfantom** [comment]
Default alertmanager image doesn't have this problem. You can check it by running:
```
docker run -it -p 9093:9093 quay.io/prometheus/alertmanager
```

**Comment by simonpasquier** [comment]
The `--cluster.listen-address` and `--web.external-url` flags are unrelated, I don't think that https://github.com/prometheus/alertmanager/commit/78c9ebc621c2f2bd6fc90d351c4e4675b583fe56 is involved here.
As @gajowi noted, HA is enabled by default, the rationale being that you can start the first instance in listen-only mode and let others join it after. With HA enabled, the memberlist library will try to find a valid advertise address (unless one is provided by `--cluster.advertise-address`) and will fail if no valid address exists. The latter happens when the box doesn't have an IP address that is part of RFC 6980 with a default route. Starting AlertManager with `--cluster.listen-address=""` disables HA altogether.

**Comment by paulfantom** [comment]
Thanks, @simonpasquier!

@gajowi could you create a PR with a fix you proposed in the initial message?

**Comment by gajowi** [comment]
fixed
