### ISSUE TITLE
RFE: Add a way to create silences from ansible

### ISSUE THREAD

**Issue by paulfantom** [cloudalchemy/ansible-alertmanager#94]
It might be beneficial to add an option to create silences from ansible.

What needs to be researched:
- checking if silence if already added
- adding silences
- figure out silence format/model for storing in ansible variable

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
